### ISSUE TITLE
Kriterien für Fertigstellung

### ISSUE THREAD

**Issue by arpad-m** [arpad-m/dontfall#13]
- [x] Punkt zwei von #6 lösen (ce93177861956737462b2108ffb060bfa4738f27)
- [x] Display-y soll automatisch nach oben gehen wenn der spieler nach oben springt (f42acb1dc425a37d7b75726a2434c1af2e432976)
- [x] Plattformen sollen nicht in der Mitte des spielfeldes erscheinen, sie sollen von oben einfliegen. (ac0b5b97e34b5c1b0eb8d5d2aba25c54dd712dba)
- [x] Das in commit 119a28afd8ccb825a0d15394c4a30931b5bd8e9c beschriebene Problem lösen, momentan ist leider etwas glück dabei wenn man nicht durch plattformen hindurchfällt. (26387962c3e33e80b5137c78e68b4318edf73387)
- [x] Geschwindigkeit soll sich mit ansteigender Höhe erhöhen (814274daf22553393fcff2fa49470bfffc7bd5a2)

**Comment by arpad-m** [comment]
Klingen diese Kriterien ok @jvoigtlaender ?

**Comment by jvoigtlaender** [comment]
Ja, absolut.

**Comment by arpad-m** [comment]
Ok, alles erledigt.
