### ISSUE TITLE
Wechsel zu AnimationFrame.times oder AnimationFrame.diffs

### ISSUE THREAD

**Issue by jvoigtlaender** [arpad-m/dontfall#2]
Aus einer meiner Emails an alle Studierende:

> 1. Wenn Sie ein Spiel mit Animationen o.ä. implementieren,
>    verwenden Sie nicht Time.every. Darauf weist schon die
>    Dokumentation hin, siehe:
>    http://package.elm-lang.org/packages/elm-lang/core/latest/Time#every.
>    Passender sind die Funktionen aus diesem Paket:
>    http://package.elm-lang.org/packages/elm-lang/animation-frame/latest.

Es sollte ohne sonstige Änderungen in Ihrem Programm möglich sein, `Time.every (50 * Time.millisecond)` durch `AnimationFrame.times` zu ersetzen.

Wenn Sie letztlich sowieso nur Time-Deltas verwenden möchten, nicht die Absolutzeit, könnten Sie sogar unter Verwendung von `AnimationFrame.diffs` auf das Feld `time` in `GameData` verzichten und für die Berechnung von `pixeldiff` in `stepTime` jeweils direkt das durch `AnimationFrame.diffs` gelieferte Delta nehmen.

**Comment by arpad-m** [comment]
Wird gefixt
