### ISSUE TITLE
"statische Randomness"

### ISSUE THREAD

**Issue by jvoigtlaender** [arpad-m/dontfall#5]
Sie führen aktuell bei jedem Aufruf von `renderScene` (also wohl 50-60 mal per Sekunde) die gesamte `background`-Erzeugung neu aus, inklusive des Auswürfelns der Positionen und Größen der Sterne. Dabei ändert sich der Hintergrund ja über den Programmverlauf gar nicht. Besser wäre daher sicher, das in die Initialisierung zu verschieben, also nur einmal auszuwürfeln und zu erzeugen und dann direkt den `Form` im Modell zu speichern.

Das würde auch die Merkwürdigkeit beheben, dass Sie aktuell zwei `initialSeed`s haben. Wandert `background` in `initGameData`, können Sie dort mittels `step` aus einem einzigen `initialSeed` sowohl den `background` als auch `worldrand` erzeugen.

Der nächste Schritt wäre dann, `initialSeed` veränderlich zu machen. Ein sinnvoller Weg dafür wäre, von `Html.App.program` zu `Html.App.programWithFlags` zu wechseln. Dann können sie nämlich aus Ihrem `index.html` heraus beim `fullscreen()`-Aufruf Werte nach Elm übergeben. Und das könnte dann für `initialSeed` statt einer Konstante sinnvollerweise ein Ausdruck mit der JavaScript-Funktion `Math.random()` sein. Dann hat wirklich jede Ausführung des Elm-Programms andere Zufallswerte.

**Comment by jvoigtlaender** [comment]
Übrigens könnten Sie über `Html.App.programWithFlags` natürlich auch andere "Konfigurationskonstanten" (wie `height` und `width`) aus dem `index.html` heraus setzen. Das macht das Programm insgesamt besser konfigurierbar, da dann keine Neuübersetzung der Elm-Komponente nötig ist um diese Parameter zu ändern.

**Comment by arpad-m** [comment]
> Sie führen aktuell bei jedem Aufruf von renderScene (also wohl 50-60 mal per Sekunde) die gesamte background-Erzeugung neu aus, inklusive des Auswürfelns der Positionen und Größen der Sterne. 

Hat elm keine lazy evaluation?

> Das würde auch die Merkwürdigkeit beheben, dass Sie aktuell zwei initialSeeds haben.

Eigentlich passt es mir, dass der hintergrund jedes mal gleich bleibt. Ich habe ihn nur deswegen zufällig erzeugt, weil es einfacher war, die Zufällige erzeugung zu programmieren, als sich 20 koordinatenpaare auszudenken.

> Der nächste Schritt wäre dann, initialSeed veränderlich zu machen.

gute idee!

Ich habe auch noch vor, die plaftform-erzeugung zu verbessern. Sie ist ja nicht nur fps-abhängig (was generell nicht gut ist), sondern die erzeugten Plattformen überlappen sich auch, und es ist nicht sichergestellt dass man immer Plattformen in der nähe hat auf die man springen kann.

**Comment by jvoigtlaender** [comment]
> Hat elm keine lazy evaluation?

Nein, das wurde ja in der Vorlesung thematisiert. :smile:

Und selbst wenn es lazy evaluation hätte, würde das nichts ändern. Mein Kommentar zu Ihrem aktuellen Umgang mit `background` würde in Haskell genauso zutreffen. Lazy evaluation optimiert nicht verschiedene Aufrufe, zu verschiedenen Zeitpunkten, von Funktionen mit den gleichen Werten. Dazu benötigt man Memoisierung, nicht Lazy Evaluation.

**Comment by arpad-m** [comment]
Siehe commits:
- 78ea732e0d74376bdcb5761d0d0b1899041ae1af
- e929917cec8c1f18a1a9990793065a2475172622
- 303bd05b064207637c30ca7985c57ced3268fba4
