### ISSUE TITLE
etwas "Code-Kritik"

### ISSUE THREAD

**Issue by jvoigtlaender** [arpad-m/dontfall#8]
Ich würde in der Regel mit Record-Patternmatching arbeiten, zum Beispiel:

``` elm
initGameData : InitFlags -> (GameData, Cmd GameMsg)
initGameData { width, height, seed } = ... width ...
```

statt:

``` elm
initGameData : InitFlags -> (GameData, Cmd GameMsg)
initGameData initFl = ... initFl.width ...
```

Das funktioniert ja sogar falls die Funktion mal nicht jede Komponente des Records benutzt. Und falls Sie auch noch Zugriff auf das `initFl` als Ganzes brauchen, geht das ja per `as`-Matching.

Ich fände es besser, die "Standardnamen" für diverse Aspekte des Programms zu benutzen. Also `Model` statt `GameData` und `Msg` statt `GameMsg`, und `view` statt `render` etc. Falls Sie die Pre- und Postfixe für nötig halten mit Blick auf mögliche Erweiterungen (also dass es abseits des eigentlichen Spiels vielleicht noch ein Hauptmenü, dann mit `MenuData` und `MenuMsg`, geben soll): Modul-Qualifizierung wäre dann die passendere Variante. Also dann hätten Sie eben Module `Game` und `Menu`, beide mit je einem `Model`\- und `Msg`-Typ, und würden die Dinge als `Game.Model` und `Menu.Msg` verwenden, und analog für eventuelle mehrere `init`-, `view`-, `update`-Funktionen.

Sind Sie sicher, dass Sie bei dem Mausereignis `"clientX"` wollen, nicht `"offsetX"`?

**Comment by arpad-m** [comment]
Ja, `offsetX` sieht viel besser aus. Siehe 5654abc629b4bd78fc3e0c866b1fe7a2ee9174f5

> Ich würde in der Regel mit Record-Patternmatching arbeiten.

Gute Idee, in dem Beispiel habe ich es geändert: 6157ab958d7f0ecadc4866ec884b26a2f079e6db

Ich habe auch an anderen Stellen nachgesehen, aber dort ist es weniger hilfreich.

> Ich fände es besser, die "Standardnamen" für diverse Aspekte des Programms zu benutzen.

Die Standardnamen sind m. A. nach nicht sehr aussagend. Evtl. ist es anders wenn man viel Elm-code liest/schreibt, aber für mich der bisher wenig mit Elm gemacht hat ist es eher verwirrend die Standardnamen zu verwenden. Am Anfang war ich sogar verwirrt was denn der `msg`-typ sein soll, bis ich herausfand dass ich den selbst definieren muss.

**Comment by jvoigtlaender** [comment]
> Die Standardnamen sind m. A. nach nicht sehr aussagend. Evtl. ist es anders wenn man viel Elm-code liest/schreibt, aber für mich der bisher wenig mit Elm gemacht hat ist es eher verwirrend die Standardnamen zu verwenden.

Aber nun dürfte die Verwirrung ja vorbei sein? :smile:

Und Code wird in der Regel mehr gelesen (von mehr Leuten) als geschrieben. Daher macht es Sinn, bei der Namenswahl eher an das "Publikum" zu denken. Und das wird mit `Model` mehr als mit `GameData` anfangen können. Und auf `Msg` trifft Ihr Argument ja sowieso nicht zu, denn `GameMsg` kann ja kaum klarer sein als `Game.Msg` (wo darüber hinaus ein Sprachmittel, nämlich Modul-Scoping, verwendet wird statt einer künstlichen Namenskonvention des `Game` Prefixes als "String").

**Comment by jvoigtlaender** [comment]
Noch zum Record-Matching:

> Ich habe auch an anderen Stellen nachgesehen, aber dort ist es weniger hilfreich.

Für wen? Für Leser des Codes ist es hilfreich, wenn direkt in der ersten Zeile der Funktionsdefinition klar ist, welche Felder eines Eingabe-Records in der Funktion verwendet werden. Gerade da Records im Laufe der Entwicklung (auch in Ihrem Programm) nach und nach immer mehr Felder akkumulieren, weil neue Features hinzukommen. Als Leser des Codes kann ich (bei Verwendung von Record-Patternmatching) entweder in der ersten Zeile der Funktion sehen, welche Teilmenge an Feldern relevant ist, oder (ohne Record-Patternmatching)  die gesamte Definition der Funktion linear scannen und mir die ganzen Stellen raussuchen, an denen `d.dies` und `d.das` etc. steht...

**Comment by arpad-m** [comment]
Für `renderScene` zum Beispiel müsste ich 8 Felder der 14 Felder in `GameData` in der Funktionsdefinition abschreiben.

Wegen des scan-Arguments: mein Text-editor (Kate) hat ein feature, das wenn man ein Wort auswählt, es weitere Vorkommen des Wortes hervorhebt:
![screenshot_20160701_083505](https://cloud.githubusercontent.com/assets/19521842/16513698/f8e49b6c-3f66-11e6-9133-a736fe95ecb5.png)
(Kate hat (noch?) kein syntax-highlighting für Elm :().

Record-Matching ist denke ich vor allem nützlich wenn man weniger variablen verwendet, diese aber öfter benutzt. Dann spart man sich das `d.` jedes mal auszuschreiben.
In diesen Fällen werde ich Record-Matching auf jeden Fall benutzen.

**Comment by jvoigtlaender** [comment]
Ist okay. (Leser Ihres Codes, zum Beispiel die anderen Studierenden, werden den Code natürlich in der Regel nicht in einem Texteditor offen haben, sondern als statische Seite etwa in GitHub sehen.)

Natürlich könnte man argumentieren, dass das mit den "8 von 14" vielleicht darauf hinweist, dass dieser große Record-Typ dekomponiert werden könnte. Also vielleicht sollte der nicht flach aus 14 Feldern bestehen, sondern aus weniger Feldern, die jeweils selbst wieder Records sind, die ihrerseits bestimmte Aspekte des Modells aggregieren. Also zum Beispiel könnte es statt der vier Felder `width`, `height`, `flWidth`, `flHeight` ein einzelnes Feld `dimensions` geben, welches eine Record ist mit diesen vier Teilfeldern. Das würde womöglich auch den Tradeoff-Punkt verschieben, ab wann es für konkrete Funktionen Sinn macht, Record-Patternmatching zu nehmen.

Und nur noch eine Kleinigkeit, zu

> Dann spart man sich das `d.` jedes mal auszuschreiben.

Man spart sich natürlich auch das wiederholte Auswerten dieser Projektion. Das ist ja jedesmal ein Dekonstruieren des Records (und eventuell ist das in der Elm-zu-JS-Übersetzung nicht direkt der billigst mögliche JS-Recordzugriff). Also, nur einmal zu matchen und dann die Komponenten mehrmals zu verwenden dürfte auch etwas effizienter sein als mehrmals die Projektionen `d.` hinzuschreiben. Aber das sollte nicht ausschlaggebend sein.

**Comment by arpad-m** [comment]
Ich denke, ich habe alles was ich mir von den Vorschlägen zur Umsetzung vorgenommen habe, umgesetzt.

Die {} - Notation sollte nun öfter im code zu finden sein.

Wegen Standardnamen: mir gefällt es so besser :)
