### ISSUE TITLE
Umgang mit Seeds/Randomness

### ISSUE THREAD

**Issue by jvoigtlaender** [arpad-m/dontfall#9]
... scheint mir konzeptionell falsch.

Sinnvoller Umgang mit Randomness ist generell: "never duplicate a seed".

Dass Sie den übergebenen Seed an zwei Stellen speichern/übergeben, und dass das Programm zur Laufzeit mehrere Aufrufe von `initialSeed` ausführt mit "parallel" (statt "sequentiell") aus dem gleichen ursprünglichen Seed gewonnenen Pseudo-Seeds, und dass Sie Aufrufe der Form `let (s, _) = step ... ... in ...` haben (also gesteppte Seeds verwerfen), das alles sind "Smells", dass Sie gegen den eigentlichen Sinn des Randomness-APIs arbeiten.

Wenn der Grund für all dies ist, dass Sie nicht die manuelle "Verwaltung" und Weiterreichen von Seed-Werten ausprogrammieren möchten (wobei, vorher taten Sie das ja - und es schien nicht weiter problematisch), dann sollten Sie sich überlegen, das in `core` ja auch unterstützte alternative API über die `generate`-Funktion zu verwenden, bei der das Seed-Management hinter den Kulissen passiert ohne Involvierung des Nutzers: http://package.elm-lang.org/packages/elm-lang/core/4.0.1/Random#generate. (Siehe auch das Beispiel aus der Vorlesung, wo Randomness genau so genutzt wurde.)

**Comment by arpad-m** [comment]
Ja, momentan verwende der code die randomness-API lediglich um aus einem Int, der mittels einer hash-funktion für jede position individuell berechnet wird, einen int/bool im gewünschten Bereich zu erzeugen.

> Wenn der Grund für all dies ist, dass Sie nicht die manuelle "Verwaltung" und Weiterreichen von Seed-Werten ausprogrammieren möchten

Ja, das war einer der Hauptgründe. Der zweite war dass man mit dem hash sich sicherer sein kann 100% nur vom seed abhängige plattformen zu erzeugen. Die Dokumentation von `Random.list` zum beispiel schweigt sich aus in welcher Reihenfolge die parameter aufgerufen werden. Erzeugt etwa `Random.map2 (++) (Random.list 10 a) (Random.list 10 a)` die gleiche Liste für gleiche seeds wie `Random.list 20 a`?

**Comment by arpad-m** [comment]
Das `pixeldiff`, das an `addNewPlatforms` übergeben wird ist ja letztendlich von der FPS abhängig. `pixeldiff` bestimmt jedoch wie groß die Intervalle die an `rangeTo` übergeben werden sind. Eine Implementierung mit der Random-API von `core` würde statt `rangeTo` `Random.list` verwenden

**Comment by jvoigtlaender** [comment]
Dieses Argument verstehe ich nicht:

> Der zweite war dass man mit dem hash sich sicherer sein kann 100% nur vom seed abhängige plattformen zu erzeugen. Die Dokumentation von `Random.list` zum beispiel schweigt sich aus in welcher Reihenfolge die parameter aufgerufen werden. Erzeugt etwa `Random.map2 (++) (Random.list 10 a) (Random.list 10 a)` die gleiche Liste für gleiche seeds wie `Random.list 20 a`?

Bzw., die Frage am Ende halte ich für nicht relevant. Es geht um Randomness. Diese Reihenfolgenfrage sollte die Semantik des Programms absolut nicht verändern (die probabilistische Semantik natürlich, also wo man nur über Wahrscheinlichkeitsverteilungen von Werten nachdenken würde). Wenn es für die Interpretation Ihres Programms also einen Unterschied machen würde, wie diese beiden Ausdrücke implementiert sind, spräche das für mich für eine Modellierungsunsicherheit.

Aber ich will auch nicht verschweigen, dass ich mich um genau diesen Punkt schon mit anderen "gestritten" habe, man also offenbar auch anderer Meinung sein kann. :smile:

https://github.com/elm-lang/core/pull/575

**Comment by jvoigtlaender** [comment]
Und das Argument mit `pixeldiff` ist, dass die genaue FPS ja auch eine Art Zufallsgröße ist, die dann mit in die Erzeugung hinein spielt?

**Comment by jvoigtlaender** [comment]
Ersetzt durch https://github.com/arpad-m/dontfall/pull/14.

**Comment by jvoigtlaender** [comment]
Mir ist jetzt klar, was Sie mit "Wohldefiniertheit der Plattformabfolge" und "Einfluss von FPS darauf" meinten. Ich sehe es aber nicht als Problem an.
